In [19]:

import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.callbacks import TensorBoard
tensorboard_callback = TensorBoard('.logdir')


### First Deep Learning Model

In [20]:

# Defining the Hyper Parameters
EPOCHS = 20
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2
DROPOUT = 0.5


In [21]:
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [22]:
# Reshaping the data
RESHAPED = 784
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')


In [5]:
# Normalizing the data
X_train, X_test = X_train/ 255.0, X_test / 255.0
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')


60000 train samples
10000 test samples


In [6]:
# to one-hot
# number of classes is based on the number of digits in the dataset
Y_train = tf.keras.utils.to_categorical(Y_train, NB_CLASSES)
Y_test = tf.keras.utils.to_categorical(Y_test, NB_CLASSES)

In [10]:
# Building the first model

model = tf.keras.models.Sequential()
model.add(keras.layers.Dense(N_HIDDEN, input_shape=(RESHAPED,), name='dense_layer', activation='relu' ))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(N_HIDDEN, name='dense_layer_2', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(NB_CLASSES, name='dense_layer_3', activation='softmax'))


In [11]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 128)               100480    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.fit(X_train, Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS, verbose=VERBOSE, validation_split=VALIDATION_SPLIT, callbacks=[tensorboard_callback])

Epoch 1/20
375/375 [==============================] - 3s 5ms/step - loss: 0.7024 - accuracy: 0.7771 - val_loss: 0.2246 - val_accuracy: 0.9341
Epoch 2/20
375/375 [==============================] - 2s 5ms/step - loss: 0.3407 - accuracy: 0.9019 - val_loss: 0.1728 - val_accuracy: 0.9506
Epoch 3/20
375/375 [==============================] - 2s 4ms/step - loss: 0.2781 - accuracy: 0.9183 - val_loss: 0.1466 - val_accuracy: 0.9581
Epoch 4/20
375/375 [==============================] - 2s 4ms/step - loss: 0.2404 - accuracy: 0.9293 - val_loss: 0.1306 - val_accuracy: 0.9617
Epoch 5/20
375/375 [==============================] - 2s 5ms/step - loss: 0.2154 - accuracy: 0.9367 - val_loss: 0.1233 - val_accuracy: 0.9640
Epoch 6/20
375/375 [==============================] - 2s 5ms/step - loss: 0.1956 - accuracy: 0.9413 - val_loss: 0.1150 - val_accuracy: 0.9657
Epoch 7/20
375/375 [==============================] - 2s 4ms/step - loss: 0.1831 - accuracy: 0.9455 - val_loss: 0.1092 - val_accuracy: 0.9678
Epoch 

In [14]:
test_loss, test_acc = model.evaluate(X_test, Y_test)
print('Test accuracy:', test_acc)
predictions = model.predict(X_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0855 - accuracy: 0.9747
Test accuracy: 0.9746999740600586
313/313 [==============================] - 0s 1ms/step


## The Second Model

In [23]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.optimizers import SGD


In [24]:

# Defining the Hyper Parameters
EPOCHS = 20
BATCH_SIZE = 256
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2
DROPOUT = 0.3
OPTIMIZER = SGD(lr=0.001)



In [25]:
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()


In [26]:

RESHAPED = 784
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')


In [27]:
X_train, X_test = X_train / 255.0, X_test / 255.0
print(X_train.shape[0], 'train samples')
print(X_test.shape[0] , 'test samples')

60000 train samples
10000 test samples


In [28]:
# Converting to one hot
Y_train = tf.keras.utils.to_categorical(Y_train, NB_CLASSES)
Y_test = tf.keras.utils.to_categorical(Y_test, NB_CLASSES)

In [30]:

model = tf.keras.models.Sequential()
model.add(keras.layers.Dense(N_HIDDEN, input_shape=(RESHAPED,), name='dense_layer', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(N_HIDDEN, name='dense_layer_2', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(NB_CLASSES, name='dense_layers_3', activation='softmax'))


In [31]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 128)               100480    
                                                                 
 dropout_3 (Dropout)         (None, 128)               0         
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dropout_5 (Dropout)         (None, 128)               0         
                                                                 
 dense_layers_3 (Dense)      (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118

In [32]:
model.compile(optimizer=OPTIMIZER, loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
model.fit(X_train, Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS, verbose=VERBOSE, validation_split=VALIDATION_SPLIT)

Epoch 1/20
188/188 [==============================] - 2s 7ms/step - loss: 2.1433 - accuracy: 0.2337 - val_loss: 1.7533 - val_accuracy: 0.6799
Epoch 2/20
188/188 [==============================] - 1s 6ms/step - loss: 1.6369 - accuracy: 0.4909 - val_loss: 1.1253 - val_accuracy: 0.7830
Epoch 3/20
188/188 [==============================] - 1s 6ms/step - loss: 1.2453 - accuracy: 0.6047 - val_loss: 0.7878 - val_accuracy: 0.8328
Epoch 4/20
188/188 [==============================] - 1s 8ms/step - loss: 1.0213 - accuracy: 0.6730 - val_loss: 0.6294 - val_accuracy: 0.8529
Epoch 5/20
188/188 [==============================] - 1s 7ms/step - loss: 0.9027 - accuracy: 0.7116 - val_loss: 0.5429 - val_accuracy: 0.8643
Epoch 6/20
188/188 [==============================] - 1s 6ms/step - loss: 0.8107 - accuracy: 0.7438 - val_loss: 0.4826 - val_accuracy: 0.8750
Epoch 7/20
188/188 [==============================] - 1s 6ms/step - loss: 0.7445 - accuracy: 0.7655 - val_loss: 0.4427 - val_accuracy: 0.8832
Epoch 

In [34]:
test_loss, test_acc = model.evaluate(X_test, Y_test)
print('Test accuracy: ', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.2763 - accuracy: 0.9193
Test accuracy:  0.9193000197410583


In [35]:
prediction = model.predict(X_test)

313/313 [==============================] - 0s 1ms/step


## Third Deep Learning Model with Distribution Strategy

In [37]:
N_TRAIN_EXAMPLES = 1024*1024
N_FEATURES = 10
SIZE_BATCHES = 256

# generating the distributed data
x = np.random.random((N_TRAIN_EXAMPLES, N_FEATURES))
y = np.random.randint(2, size=(N_TRAIN_EXAMPLES, 1))
x = tf.dtypes.cast(x, tf.float32)
print(x)

tf.Tensor(
[[0.19605176 0.32098588 0.5565651  ... 0.6678118  0.6509347  0.40295428]
 [0.00672834 0.60890687 0.5970018  ... 0.33838442 0.4008075  0.7016951 ]
 [0.30655473 0.45009416 0.40060434 ... 0.3938137  0.90638614 0.30166543]
 ...
 [0.1854783  0.6003934  0.5425693  ... 0.01046163 0.42967808 0.29364613]
 [0.77614826 0.29938215 0.5790488  ... 0.9813458  0.07891549 0.6953051 ]
 [0.8370791  0.2547559  0.73152065 ... 0.61183494 0.8983542  0.94695103]], shape=(1048576, 10), dtype=float32)


In [39]:
dataset = tf.data.Dataset.from_tensor_slices((x, y))
# shuffling the dataset
dataset = dataset.shuffle(buffer_size=N_TRAIN_EXAMPLES).batch(SIZE_BATCHES)

In [40]:
distribution = tf.distribute.MirroredStrategy()

In [41]:
with distribution.scope():
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Dense(16, activation='relu', input_shape=(N_FEATURES, )))
  model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
  optimizer = tf.keras.optimizers.SGD(0.2)
  model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [42]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                176       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 193 (772.00 Byte)
Trainable params: 193 (772.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [43]:
model.fit(dataset, epochs=20, steps_per_epoch=100)

Epoch 1/20
100/100 [==============================] - 2s 2ms/step - loss: 0.6953
Epoch 2/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6952
Epoch 3/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6937
Epoch 4/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6942
Epoch 5/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6935
Epoch 6/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6934
Epoch 7/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6936
Epoch 8/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 9/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6934
Epoch 10/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 11/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6936
Epoch 12/20
100/100 [==============================] - 0s 2ms/step - loss: 0.6934
Epoch 13/20
100/100 [====